#!/bin/bash

# Abort script on first error
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/globals

GAME=${1%/}
COMMAND=${2,,}
LAUNCHER=${3,,}

if [[ -z "${STEAM_USERNAME// }" ]]; then
	error "No Setam username configured in 'game-servers/linux/global'"
	exit
fi

# Check 2 arguments are given #
if [ $# -lt 2 ]
then
	info ""
        info "Usage : game-servers [game server folder] [command] [launcher]"
	info ""
	info "Commands : install update launch console"
	info ""
        exit
fi

function launch {
	if [ ! -d "$2/logs" ]; then
		mkdir -p "$2/logs"
	fi
        tmux new-session -d -s "$2-$3" "$1" 2> "$2/logs/$2-$3-tmux-error.log"
}

function console {
        tmux attach-session -t "$1-$2"
}

function stop {
	tmux send-keys "^c" -t "$1-$2"
}

if [[ -z "${LAUNCHER// }" ]]; then
	LAUNCHER="default"
fi

case $COMMAND in
    "install")
	if [ -f $DIR/$GAME/install.sh ]; then
            info "Installing $GAME server"
	    source $DIR/$GAME/install.sh
	else
            error "Installer for $GAME not found"
	fi
        ;;

    "update")
        if [ -f $DIR/$GAME/update.sh ]; then
            info "Updating $GAME server"
            source $DIR/$GAME/update.sh
	else
            error "Updater for $GAME not found"
        fi
        ;;

    "launch")
        if [ -f $DIR/$GAME/launchers/$LAUNCHER.sh ]; then
		if (tmux has-session -t "$GAME-$LAUNCHER" 2> /dev/null); then
	            error "Server $GAME-$LAUNCHER already running"
		else
	            info "Launching $GAME server with \"$LAUNCHER\" launcher"
                    launch "$DIR/$GAME/launchers/$LAUNCHER.sh" "$GAME" "$LAUNCHER"
		fi
        else
            error "Launcher \"$LAUNCHER\" for $GAME not found"
        fi
        ;;

    "stop")
	info "Stopping $GAME ($LAUNCHER) server"
	stop "$GAME" "$LAUNCHER"
	exit
	;;

    "console")
        info "Opening console for $GAME ($LAUNCHER) server"
	info "Press ctrl+b and then d to exit the console but leave the server running"
	info "If you press ctrl+c the server will stop!"
	info "Please wait..."
	sleep 2
        console "$GAME" "$LAUNCHER"
        ;;

    *)
        error "Unknown command: $COMMAND"
	exit
        ;;
esac

